#!/usr/bin/env bash

function mygrep {
if [ $# = 1 ]
then
	echo "find . -exec grep -i \"$1\" {} /dev/null \\;"
	find . -exec grep -n "$1" {} /dev/null \; 2> /dev/null | grep -v "/tags:" | grep -v "/.tags:" | grep -v .svn | grep -v .git | grep -v "Binary file" | grep -v nosetests.xml | grep --color "$1"
else
	echo "find . -name \"$2\" -exec grep -i \"$1\" {} /dev/null \\;"
	find . -name "$2" -exec grep -n "$1" {} /dev/null \; 2> /dev/null | grep -v "/tags:" | grep -v "/.tags:" | grep -v .svn | grep -v .git | grep -v "Binary file" | grep -v nosetests.xml | grep --color "$1"
fi
}

